;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+CommonlyReplicatedTags=State.HitReact
+CommonlyReplicatedTags=State.HitReact.Stun
+CommonlyReplicatedTags=State.Debuff.Burn
+CommonlyReplicatedTags=State.Block.Movement
+CommonlyReplicatedTags=State.Block.Movement.Speed
+CommonlyReplicatedTags=State.Block.Movement.Rotation
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AI.Event.Detected",DevComment="When AI detect target and leave neautral state")

